include versions
export BACKPORTS_VERSION BACKPORTED_KERNEL_VERSION BACKPORTED_KERNEL_VERSION_CODE BACKPORTED_KERNEL_NAME
ifdef BACKPORTS_GIT_TRACKED
export BACKPORTS_GIT_TRACKER_DEF=-DBACKPORTS_GIT_TRACKED=\"$(BACKPORTS_GIT_TRACKED)\"
else
export BACKPORTS_GIT_TRACKER_DEF=
endif

export LEX = flex
export YACC = bison

# disable built-in rules for this file
.SUFFIXES:

export CONFIG_=CPTCFG_

kconf/mconf kconf/conf:
	@$(MAKE) --no-print-directory -C kconf $(@F)

.PHONY: menuconfig
menuconfig: kconf/mconf
	./kconf/mconf Kconfig

.PHONY: listnewconfig oldaskconfig oldconfig \
	olddefconfig oldnoconfig \
	allnoconfig allyesconfig allmodconfig \
	alldefconfig randconfig

listnewconfig oldaskconfig oldconfig \
olddefconfig oldnoconfig \
allnoconfig allyesconfig allmodconfig \
alldefconfig randconfig: kconf/conf
	./kconf/conf --$@ Kconfig

.PHONY: usedefconfig
usedefconfig: kconf/conf
	./kconf/conf --defconfig=defconfig Kconfig

.PHONY: savedefconfig
savedefconfig: kconf/conf
	./kconf/conf --savedefconfig=defconfig Kconfig

defconfig-%:: kconf/conf
	./kconf/conf --defconfig=defconfigs/$(@:defconfig-%=%) Kconfig

.config: Kconfig.versions Kconfig.kernel
ifneq ($(wildcard .config),)
	$(MAKE) -f Makefile.real oldconfig
else
	@test -f defconfig && $(MAKE) usedefconfig || (			\
	echo "/--------------"						;\
	echo "| Your backport package isn't configured, please configure it" ;\
	echo "| using one of the following options:"			;\
	echo "| To configure manually:"					;\
	echo "|     make oldconfig"					;\
	echo "|     make menuconfig"					;\
	echo "|"							;\
	echo "| To get defaults for certain drivers:"			;\
	(cd defconfigs ; for f in $$(ls) ; do				\
		echo "|     make defconfig-$$f"				;\
	done )								;\
	echo "\--"							;\
	false )
endif

.PHONY: syncconfig
syncconfig: backport-include/backport/autoconf.h backport-include/backport/auto.conf

backport-include/backport/autoconf.h: .config
	@echo -n "Building backport-include/backport/autoconf.h ..."
	@grep -f local-symbols .config | (				\
		echo "#ifndef COMPAT_AUTOCONF_INCLUDED"			;\
		echo "#define COMPAT_AUTOCONF_INCLUDED"			;\
		echo "/*"						;\
		echo " * Automatically generated file, don't edit!"	;\
		echo " * Changes will be overwritten"			;\
		echo " */"						;\
		echo ""							;\
		while read l ; do					\
			n=$${l%%=*}					;\
			v=$${l#*=}					;\
			case $$v in					\
				y) echo "#define $$n 1" ;;		\
				m) echo "#define $${n}_MODULE 1" ;;	\
				\"*) echo "#define $$n $$v" ;;		\
				[0-9]*) echo "#define $$n $$v" ;;	\
				*) echo "#warning unknown value for $$n";;\
			esac						;\
		done							;\
		echo "#endif /* COMPAT_AUTOCONF_INCLUDED */"		;\
	) > backport-include/backport/autoconf.h
	@echo " done."

backport-include/backport/auto.conf: .config
	@echo -n "Building backport-include/backport/auto.conf ..."
	@sed -n 's/^\(CPTCFG_.*=.*\)/export \1/p' .config > backport-include/backport/auto.conf
	@echo " done."

.PHONY: modules
modules: syncconfig
	@$(MAKE) -C $(KLIB_BUILD) M=$(BACKPORT_DIR) modules

.PHONY: modules_install
modules_install: modules
	@$(MAKE) -C $(KLIB_BUILD) M=$(BACKPORT_DIR)			\
		INSTALL_MOD_DIR=$(KMODDIR) $(KMODPATH_ARG)		\
		modules_install

_deb_arch_x86_64  := amd64
_deb_arch_i386    := i386
_deb_arch_arm64   := arm64
_deb_arch_aarch64 := arm64
_deb_arch_arm     := armhf
_deb_arch_riscv64 := riscv64
DEB_ARCH          ?= $(or $(_deb_arch_$(ARCH)),$(shell dpkg --print-architecture))

_PKG_STAGING := $(BACKPORT_DIR)/.pkg

.PHONY: deb-pkg
deb-pkg: KMODPATH_ARG = INSTALL_MOD_PATH="$(_PKG_STAGING)"
deb-pkg: modules_install
	$(if $(shell command -v dpkg-deb 2>/dev/null),,$(error dpkg-deb is required to build Debian packages))
	$(eval _pkg_krel := $(shell $(MAKE) --no-print-directory -C $(KLIB_BUILD) kernelrelease 2>/dev/null))
	$(eval _pkg_name := $(shell printf 'summit-linux-backports-%s' \"$(_pkg_krel)\" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9.+-]/-/g'))
	$(eval _pkg_ver  := $(shell echo "$(BACKPORTS_VERSION)" | sed -rn 's/.*([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+).*/\1/p'))
	$(eval _pkg_out  := $(BACKPORT_DIR)/$(_pkg_name)_$(_pkg_ver)_$(DEB_ARCH).deb)
	@mkdir -p "$(_PKG_STAGING)/DEBIAN"
	@{ \
		echo "Package: $(_pkg_name)"; \
		echo "Version: $(_pkg_ver)"; \
		echo "Section: kernel"; \
		echo "Priority: optional"; \
		echo "Architecture: $(DEB_ARCH)"; \
		echo "Maintainer: Summit Backports <support@ezurio.com>"; \
		echo "Description: Backported kernel modules for $(_pkg_krel)"; \
		echo " This package contains backported wireless and related kernel modules."; \
	} > "$(_PKG_STAGING)/DEBIAN/control"
	@printf '#!/bin/sh\ndepmod -a "$(_pkg_krel)"\n' > "$(_PKG_STAGING)/DEBIAN/postinst"
	@chmod 0755 "$(_PKG_STAGING)/DEBIAN/postinst"
	@cp "$(_PKG_STAGING)/DEBIAN/postinst" "$(_PKG_STAGING)/DEBIAN/postrm"
	@dpkg-deb --root-owner-group --build "$(_PKG_STAGING)" "$(_pkg_out)" >/dev/null
	@rm -rf "$(_PKG_STAGING)"
	@echo "Created Debian package: $(_pkg_out)"

.PHONY: install
install: modules_install
	@./scripts/blacklist.sh $(KLIB)/ $(KLIB)/$(KMODDIR)
	@./scripts/compress_modules.sh $(KLIB)/$(KMODDIR)
	@./scripts/check_depmod.sh
	@/sbin/depmod -a
	@./scripts/update-initramfs.sh $(KLIB)
	@echo
	@echo Your backported driver modules should be installed now.
	@echo Reboot.
	@echo

.PHONY: uninstall
uninstall:
	@./scripts/uninstall.sh
	@/sbin/depmod -a
	@./scripts/update-initramfs.sh $(KLIB)
	@echo
	@echo Your backported driver modules should be uninstalled now.
	@echo Reboot.
	@echo

.PHONY: clean
clean:
	@$(MAKE) -C $(KLIB_BUILD) M=$(BACKPORT_DIR) clean
	@$(MAKE) -C kconf clean
